# Generated by Django 5.2.7 on 2025-12-25 17:24

import django.db.models.deletion
import file.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ファイル表示名')),
                ('attached_file', models.FileField(max_length=255, upload_to=file.models.file_upload_path, verbose_name='ファイル')),
                ('publication_scope', models.CharField(choices=[('private', '非公開（自校のみ）'), ('admin', '管理者のみ横断閲覧')], default='private', max_length=20, verbose_name='公開範囲')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='user_management.school', verbose_name='対象スクール')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
