# Generated by Django 5.2.7 on 2025-11-06 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='storage_key',
        ),
        migrations.AlterField(
            model_name='file',
            name='consent_publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
