# Generated by Django 5.2.7 on 2025-12-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='consent_publication',
            field=models.BooleanField(default=False, verbose_name='公開許可'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ファイル表示名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
