# Generated by Django 5.2.7 on 2026-01-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user_id',
        ),
    ]
