# Generated by Django 5.2.7 on 2025-12-04 09:20

import django.db.models.deletion
import file.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0002_remove_file_storage_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="file",
            name="attached_file",
            field=models.FileField(
                default="dummy_file_path.pdf",
                upload_to=file.models.file_image_path,
                verbose_name="ファイル",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="school_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="school"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成者",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="アップロード日時"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(max_length=255, verbose_name="ファイル表示名"),
        ),
        migrations.AlterField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
