# Generated by Django 5.2.7 on 2025-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.UUIDField(blank=True, help_text='将来的にSchoolモデルと紐付く予定', null=True),
        ),
    ]
