# Generated by Django 5.2.7 on 2026-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_remove_user_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
