# Generated by Django 5.2.7 on 2025-12-05 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='operator_user',
            field=models.ForeignKey(blank=True, help_text='操作を実行したユーザー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='操作対象ユーザー（該当しない場合はNULL）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
