# Generated by Django 5.2 on 2025-11-10 14:46

import django.core.validators
import django.db.models.deletion
import news.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="見出し")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="本文"),
                ),
                (
                    "importance",
                    models.BooleanField(default=False, verbose_name="重要なお知らせ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_news",
                        to="user_management.school",
                        verbose_name="対象スクール",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "お知らせ",
                "verbose_name_plural": "お知らせ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attached_file",
                    models.FileField(
                        help_text="許可ファイル: pdf, jpg, jpeg, png, gif, svg, bmp (10MB以下)",
                        upload_to=news.models.news_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "gif", "svg", "bmp"]
                            ),
                            news.models.validate_file_size,
                        ],
                        verbose_name="添付ファイル",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="news.news",
                        verbose_name="お知らせ本体",
                    ),
                ),
            ],
            options={
                "verbose_name": "添付ファイル",
                "verbose_name_plural": "添付ファイル",
            },
        ),
        migrations.CreateModel(
            name="NewsReadStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="既読日時"),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_statuses",
                        to="news.news",
                        verbose_name="お知らせ本体",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="既読ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "お知らせ既読状態",
                "verbose_name_plural": "お知らせ既読状態",
                "ordering": ["-read_at"],
                "unique_together": {("news", "user")},
            },
        ),
    ]
