# Generated by Django 5.2.7 on 2025-12-05 00:49

import django.core.validators
import news.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='見出し')),
                ('content', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('importance', models.BooleanField(default=False, verbose_name='重要なお知らせ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attached_file', models.FileField(help_text='許可ファイル: pdf, jpg, jpeg, png, gif, svg, bmp (10MB以下)', upload_to=news.models.news_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'bmp']), news.models.validate_file_size], verbose_name='添付ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
            },
        ),
        migrations.CreateModel(
            name='NewsReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='既読日時')),
            ],
            options={
                'verbose_name': 'お知らせ既読状態',
                'verbose_name_plural': 'お知らせ既読状態',
                'ordering': ['-read_at'],
            },
        ),
    ]
