# Generated by Django 5.2.7 on 2025-12-03 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_news', to='user_management.school', verbose_name='対象スクール'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='newsattachment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.news', verbose_name='お知らせ本体'),
        ),
        migrations.AddField(
            model_name='newsreadstatus',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='news.news', verbose_name='お知らせ本体'),
        ),
        migrations.AddField(
            model_name='newsreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_news', to=settings.AUTH_USER_MODEL, verbose_name='既読ユーザー'),
        ),
        migrations.AlterUniqueTogether(
            name='newsreadstatus',
            unique_together={('news', 'user')},
        ),
    ]
