# Generated by Django 5.2.7 on 2025-11-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('user_management', '0004_school_remove_user_salt_remove_user_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_news', to='user_management.school', verbose_name='対象スクール'),
        ),
    ]
