# Generated by Django 5.2.7 on 2025-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsattachment',
            options={'ordering': ['-created_at'], 'verbose_name': '添付ファイル', 'verbose_name_plural': '添付ファイル'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='本文'),
        ),
    ]
