# Generated by Django 5.2.7 on 2025-11-13 06:20

import django.core.validators
import django.db.models.deletion
import gallery.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="ギャラリー記事のタイトル",
                        max_length=255,
                        verbose_name="見出し",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="ギャラリー記事の本文 (任意)",
                        null=True,
                        verbose_name="本文",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_gallery",
                        to="user_management.school",
                        verbose_name="対象スクール",
                    ),
                ),
            ],
            options={
                "verbose_name": "ギャラリー記事",
                "verbose_name_plural": "ギャラリー記事",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_file",
                    models.FileField(
                        help_text="許可ファイル: pdf, jpg, jpeg, png, gif, svg, bmp (10MB以下)",
                        upload_to=gallery.models.gallery_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "gif", "svg", "bmp"]
                            ),
                            gallery.models.validate_file_size,
                        ],
                        verbose_name="添付画像",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="gallery.gallery",
                        verbose_name="ギャラリー記事",
                    ),
                ),
            ],
            options={
                "verbose_name": "ギャラリー画像",
                "verbose_name_plural": "ギャラリー画像",
            },
        ),
    ]
