# Generated by Django 5.2.7 on 2025-12-03 14:23

import django.core.validators
import gallery.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ギャラリー記事のタイトル', max_length=255, verbose_name='見出し')),
                ('content', models.TextField(blank=True, help_text='ギャラリー記事の本文 (任意)', null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ギャラリー記事',
                'verbose_name_plural': 'ギャラリー記事',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(help_text='許可ファイル: pdf, jpg, jpeg, png, gif, svg, bmp (10MB以下)', upload_to=gallery.models.gallery_image_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'bmp']), gallery.models.validate_file_size], verbose_name='添付画像')),
            ],
            options={
                'verbose_name': 'ギャラリー画像',
                'verbose_name_plural': 'ギャラリー画像',
            },
        ),
    ]
