# Generated by Django 5.2.7 on 2025-12-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_options_alter_galleryimage_options_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_items', to='user_management.school', verbose_name='対象スクール'),
        ),
    ]
