# Generated by Django 5.2.7 on 2025-12-03 14:23

import django.core.validators
import timeschedule.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeschedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='学年')),
                ('title', models.CharField(max_length=255, verbose_name='時間割表示名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimescheduleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to=timeschedule.models.timeschedule_image_path, verbose_name='時間割画像')),
            ],
        ),
    ]
