# Generated by Django 5.2.7 on 2025-12-05 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeschedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='timescheduleimage',
            name='timeschedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='timeschedule.timeschedule', verbose_name='時間割情報'),
        ),
    ]
