# Generated by Django 5.2.7 on 2025-12-11 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeschedule', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timescheduleimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
