# Generated by Django 5.2.7 on 2025-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeschedule', '0003_alter_timescheduleimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timescheduleimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
